/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Service health and capability reporting.
         */
        get: operations["health_check_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/regions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Regions
         * @description List all supported geographical and cloud regions for grid carbon intensity.
         */
        get: operations["get_regions_api_v1_regions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/presets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Metadata And Presets
         * @description Returns available models, hardware options, geographical regions,
         *     and preset scenarios (inputs only) so the frontend hardcodes nothing.
         */
        get: operations["get_metadata_and_presets_api_v1_presets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Metadata And Presets
         * @description Returns available models, hardware options, geographical regions,
         *     and preset scenarios (inputs only) so the frontend hardcodes nothing.
         */
        get: operations["get_metadata_and_presets_api_v1_meta_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ledger": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Calculate Ledger
         * @description Compute dual lifecycle ledgers (operational and full_lifecycle)
         *     for a given AI system inventory.
         */
        post: operations["calculate_ledger_api_v1_ledger_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/claims/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Check Efficiency Claim
         * @description Audit an efficiency claim against baseline and subject ledgers
         *     using the deterministic multi-tier verification cascade.
         */
        post: operations["check_efficiency_claim_api_v1_claims_check_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/claims/extract": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Extract Claim
         * @description Extract a structured Claim object from free-text marketing copy,
         *     research papers, or model cards.
         */
        post: operations["extract_claim_api_v1_claims_extract_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recommend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Recommend Architectures
         * @description Generate alternative architectures, evaluate full lifecycle ledgers,
         *     filter constraints, and compute Pareto frontier.
         */
        post: operations["recommend_architectures_api_v1_recommend_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AccountingMethod
         * @enum {string}
         */
        AccountingMethod: "location" | "market";
        /**
         * AccuracySource
         * @description How the accuracy estimate for a candidate was obtained.
         * @enum {string}
         */
        AccuracySource: "user_sample_eval" | "cited_published_delta" | "not_available";
        /**
         * Boundary
         * @enum {string}
         */
        Boundary: "operational" | "full_lifecycle";
        /** BoundaryStated */
        BoundaryStated: {
            /** Includes Training */
            includes_training?: boolean | null;
            /** Includes Embodied */
            includes_embodied?: boolean | null;
            /** Includes Retraining */
            includes_retraining?: boolean | null;
            /**
             * Accounting
             * @default unspecified
             * @enum {string}
             */
            accounting: "location" | "market" | "unspecified";
        };
        /**
         * Claim
         * @description A structured efficiency claim extracted from free text or a model card.
         *
         *     Fields left None mean the information was absent or ambiguous in the source.
         *     Never guess missing boundary fields: leave them unspecified / None.
         */
        Claim: {
            /** Claim Text */
            claim_text: string;
            /**
             * Metric
             * @enum {string}
             */
            metric: "energy" | "carbon" | "latency" | "cost";
            /** Claimed Change Pct */
            claimed_change_pct?: number | null;
            /** Baseline Ref */
            baseline_ref?: string | null;
            /** Subject Ref */
            subject_ref?: string | null;
            boundary_stated: components["schemas"]["BoundaryStated"];
            /** Hardware */
            hardware?: string | null;
            /** Region */
            region?: string | null;
            /**
             * Accuracy Change Reported
             * @default false
             */
            accuracy_change_reported: boolean;
            /** Accuracy Change Pct */
            accuracy_change_pct?: number | null;
            /**
             * Source Type
             * @default unknown
             * @enum {string}
             */
            source_type: "vendor" | "paper" | "model_card" | "blog" | "unknown";
            /** Source Url */
            source_url?: string | null;
            /**
             * Extraction Source
             * @default user_specified
             * @enum {string}
             */
            extraction_source: "gemini" | "rules_fallback" | "user_specified";
        };
        /**
         * ClaimToLedgerMapping
         * @description User-supplied mapping that links a Claim to computed LifecycleLedgers.
         *
         *     Can supply both operational ledgers (baseline_ledger, subject_ledger)
         *     and full-lifecycle ledgers (baseline_ledger_full, subject_ledger_full).
         *     If full-lifecycle ledgers are omitted, the checker uses baseline_ledger
         *     and subject_ledger under their native boundary.
         */
        ClaimToLedgerMapping: {
            claim: components["schemas"]["Claim"];
            baseline_ledger: components["schemas"]["LifecycleLedger-Input"];
            subject_ledger: components["schemas"]["LifecycleLedger-Input"];
            baseline_ledger_full?: components["schemas"]["LifecycleLedger-Input"] | null;
            subject_ledger_full?: components["schemas"]["LifecycleLedger-Input"] | null;
        };
        /** ExtractClaimRequest */
        ExtractClaimRequest: {
            /** Text */
            text: string;
        };
        /** GPUSpec */
        GPUSpec: {
            /**
             * Model
             * @description GPU model string, e.g. 'NVIDIA A100 80GB SXM4'.
             */
            model: string;
            /** Count */
            count: number;
            /**
             * Tdp W
             * @description Thermal Design Power in Watts. If None, looked up from reference table. User-supplied value takes precedence.
             */
            tdp_w?: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HardwareOption */
        HardwareOption: {
            /** Model */
            model: string;
            /** Tdp W */
            tdp_w: number;
            /** Vram Gb */
            vram_gb?: number | null;
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Version */
            version: string;
            /** Gemini Available */
            gemini_available: boolean;
            /** Gemini Model */
            gemini_model: string;
            /** Regions Count */
            regions_count: number;
        };
        /** InferenceConfig */
        InferenceConfig: {
            gpu: components["schemas"]["GPUSpec"];
            /**
             * Runtime Hours
             * @description Operational inference runtime hours (default 8760.0 = 1 year).
             * @default 8760
             */
            runtime_hours: number;
            /**
             * Batch Size
             * @default 1
             */
            batch_size: number;
            /** Requests Per Day */
            requests_per_day: number;
            /**
             * Avg Tokens Per Request
             * @default 512
             */
            avg_tokens_per_request: number;
            /**
             * P95 Latency Limit Ms
             * @description Hard latency constraint. Candidates exceeding this are excluded from Pareto.
             */
            p95_latency_limit_ms?: number | null;
        };
        /**
         * LedgerAssumptions
         * @description Every assumption that can change a number is documented here.
         *     The UI shows this block alongside any result so the user can audit it.
         */
        LedgerAssumptions: {
            grid_intensity_gco2_per_kwh: components["schemas"]["Quantity"];
            /**
             * Pue
             * @description Power Usage Effectiveness (>1.0).
             */
            pue: number;
            /**
             * Pue Source
             * @description Where this PUE value came from.
             */
            pue_source: string;
            /**
             * Utilization
             * @description Fraction of peak TDP drawn.
             */
            utilization: number;
            /** Utilization Source */
            utilization_source: string;
            /** Hardware Lifetime Years */
            hardware_lifetime_years: number;
            /** Hardware Lifetime Source */
            hardware_lifetime_source: string;
            /** Region */
            region: string;
            accounting: components["schemas"]["AccountingMethod"];
            /**
             * Monte Carlo N Samples
             * @default 1000
             */
            monte_carlo_n_samples: number;
            /**
             * Monte Carlo Seed
             * @default 42
             */
            monte_carlo_seed: number;
            /**
             * Note
             * @default All ranges labeled 'under stated assumptions'. Changing any assumption can move results outside this range.
             */
            note: string;
        };
        /**
         * LedgerEngineConfig
         * @description Overridable assumptions for the ledger engine.
         *     Defaults match the recommended values from their respective sources.
         */
        LedgerEngineConfig: {
            /** Pue */
            pue?: number | null;
            /**
             * Hardware Lifetime Years
             * @default 4
             */
            hardware_lifetime_years: number;
            /**
             * Utilization
             * @default 1
             */
            utilization: number;
            /** @default location */
            accounting: components["schemas"]["AccountingMethod"];
            /**
             * N Mc Samples
             * @default 1000
             */
            n_mc_samples: number;
            /**
             * Mc Seed
             * @default 42
             */
            mc_seed: number;
            /** Requests Per Day */
            requests_per_day?: number | null;
        };
        /** LedgerRequest */
        LedgerRequest: {
            inventory: components["schemas"]["SystemInventory"];
            config?: components["schemas"]["LedgerEngineConfig"] | null;
        };
        /** LedgerResponse */
        LedgerResponse: {
            operational: components["schemas"]["LifecycleLedger-Output"];
            full_lifecycle: components["schemas"]["LifecycleLedger-Output"];
        };
        /**
         * LifecycleLedger
         * @description Full or operational carbon/energy ledger for one AI system configuration.
         *
         *     All component fields are in kg CO2e. energy_kwh is in kWh.
         *     per_request is in kg CO2e per request.
         */
        "LifecycleLedger-Input": {
            boundary: components["schemas"]["Boundary"];
            training: components["schemas"]["Quantity"];
            inference: components["schemas"]["Quantity"];
            embodied_hardware: components["schemas"]["Quantity"];
            retraining: components["schemas"]["Quantity"];
            storage: components["schemas"]["Quantity"];
            network: components["schemas"]["Quantity"];
            energy_kwh: components["schemas"]["Quantity"];
            per_request: components["schemas"]["Quantity"];
            assumptions: components["schemas"]["LedgerAssumptions"];
            /**
             * Schema Version
             * @default 1
             */
            schema_version: number;
        };
        /**
         * LifecycleLedger
         * @description Full or operational carbon/energy ledger for one AI system configuration.
         *
         *     All component fields are in kg CO2e. energy_kwh is in kWh.
         *     per_request is in kg CO2e per request.
         */
        "LifecycleLedger-Output": {
            boundary: components["schemas"]["Boundary"];
            training: components["schemas"]["Quantity"];
            inference: components["schemas"]["Quantity"];
            embodied_hardware: components["schemas"]["Quantity"];
            retraining: components["schemas"]["Quantity"];
            storage: components["schemas"]["Quantity"];
            network: components["schemas"]["Quantity"];
            energy_kwh: components["schemas"]["Quantity"];
            per_request: components["schemas"]["Quantity"];
            assumptions: components["schemas"]["LedgerAssumptions"];
            /**
             * Schema Version
             * @default 1
             */
            schema_version: number;
            /** @description Total carbon footprint for this boundary in kgCO2e. */
            readonly total_carbon: components["schemas"]["Quantity"];
            /** @description Total energy consumption in kWh. */
            readonly total_energy: components["schemas"]["Quantity"];
        };
        /** MetadataResponse */
        MetadataResponse: {
            /** Models */
            models: components["schemas"]["ModelPreset"][];
            /** Hardware */
            hardware: components["schemas"]["HardwareOption"][];
            /** Regions */
            regions: components["schemas"]["RegionOption"][];
            /** Preset Scenarios */
            preset_scenarios: components["schemas"]["PresetScenario"][];
        };
        /** ModelPreset */
        ModelPreset: {
            /** Name */
            name: string;
            /** Family */
            family: string;
            /** Params Billions */
            params_billions: number;
            /**
             * Precision
             * @default fp16
             */
            precision: string;
        };
        /** ModelSpec */
        ModelSpec: {
            /** Name */
            name: string;
            /**
             * Family
             * @description e.g. 'llama', 'gpt', 'mistral'
             */
            family: string;
            /** Params Billions */
            params_billions: number;
            /**
             * Precision
             * @default fp16
             * @enum {string}
             */
            precision: "fp32" | "fp16" | "bf16" | "int8" | "int4";
            /**
             * Framework
             * @default pytorch
             */
            framework: string;
        };
        /**
         * ParetoResult
         * @description Pareto analysis output for the recommender screen across both boundaries.
         */
        ParetoResult: {
            boundary: components["schemas"]["Boundary"];
            /** Candidates */
            candidates: components["schemas"]["RecommenderCandidate"][];
            /** Pareto Front Labels */
            pareto_front_labels: string[];
            /** Break Even Traffic Requests */
            break_even_traffic_requests?: number | null;
            /** Winner Operational */
            winner_operational?: string | null;
            /** Winner Full Lifecycle */
            winner_full_lifecycle?: string | null;
            /**
             * Winner Changed
             * @default false
             */
            winner_changed: boolean;
            /**
             * Qualifying Candidates Count
             * @default 0
             */
            qualifying_candidates_count: number;
            /** Binding Constraint */
            binding_constraint?: string | null;
            /**
             * Rankings Operational
             * @description Ranked candidate labels sorted by operational carbon (lowest to highest).
             */
            rankings_operational?: string[];
            /**
             * Rankings Full Lifecycle
             * @description Ranked candidate labels sorted by full lifecycle carbon (lowest to highest).
             */
            rankings_full_lifecycle?: string[];
            /**
             * Pareto Points Operational
             * @description Non-dominated Pareto frontier labels under operational boundary.
             */
            pareto_points_operational?: string[];
            /**
             * Pareto Points Full Lifecycle
             * @description Non-dominated Pareto frontier labels under full lifecycle boundary.
             */
            pareto_points_full_lifecycle?: string[];
            /**
             * Break Even Operational Requests
             * @description Break-even request volume under operational boundary.
             */
            break_even_operational_requests?: number | null;
            /**
             * Break Even Full Lifecycle Requests
             * @description Break-even request volume under full lifecycle boundary.
             */
            break_even_full_lifecycle_requests?: number | null;
        };
        /** PresetScenario */
        PresetScenario: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description: string;
            inventory: components["schemas"]["SystemInventory"];
        };
        /**
         * Quantity
         * @description A single numeric estimate with uncertainty range, provenance, and tier.
         *
         *     Invariants (enforced):
         *       - low <= value <= high
         *       - unit must be a non-empty string
         *       - source must be a non-empty string
         *       - tier determines how to display confidence: 'measured' vs 'modeled'
         *
         *     The range (low, high) is the 5th-to-95th percentile range produced by
         *     Monte Carlo propagation under stated assumptions (see uncertainty.py).
         *     All modeled ranges carry the label "under stated assumptions" in the UI.
         */
        Quantity: {
            /** Value */
            value: number;
            /** Low */
            low: number;
            /** High */
            high: number;
            /** Unit */
            unit: string;
            tier: components["schemas"]["Tier"];
            /** Source */
            source: string;
            /**
             * Method Note
             * @description Short note on how this number was produced.
             * @default
             */
            method_note: string;
        };
        /** ReasonStep */
        ReasonStep: {
            /** Step */
            step: number;
            /** Check */
            check: string;
            /**
             * Result
             * @enum {string}
             */
            result: "pass" | "fail" | "warn" | "skip";
            /** Evidence */
            evidence: string;
        };
        /** RecommendRequest */
        RecommendRequest: {
            inventory: components["schemas"]["SystemInventory"];
            /** @default operational */
            boundary: components["schemas"]["Boundary"];
            /** Accuracy Floor */
            accuracy_floor?: number | null;
        };
        /**
         * RecommenderCandidate
         * @description One architecture candidate evaluated by the recommender.
         */
        RecommenderCandidate: {
            /**
             * Label
             * @description Human-readable name, e.g. 'INT8 quantized on A100'.
             */
            label: string;
            inventory: components["schemas"]["SystemInventory"];
            ledger_operational: components["schemas"]["LifecycleLedger-Output"];
            ledger_full: components["schemas"]["LifecycleLedger-Output"];
            /** Accuracy */
            accuracy?: number | null;
            /** @default not_available */
            accuracy_source: components["schemas"]["AccuracySource"];
            /**
             * Accuracy Source Citation
             * @description DOI, URL, or dataset name if accuracy_source is 'cited_published_delta'. Dataset split name if 'user_sample_eval'.
             */
            accuracy_source_citation?: string | null;
            p95_latency_ms?: components["schemas"]["Quantity"] | null;
            /**
             * Latency Constraint Met
             * @default true
             */
            latency_constraint_met: boolean;
            /** Latency Exclusion Reason */
            latency_exclusion_reason?: string | null;
            /**
             * Break Even Requests
             * @description Requests at which this candidate's full-lifecycle cost drops below the baseline operational cost. None if no training overhead.
             */
            break_even_requests?: number | null;
            /**
             * Cascade Split
             * @description Fraction of traffic handled by this (small) model in a cascade. Either user-supplied or router-model output.
             */
            cascade_split?: number | null;
            /**
             * Cascade Split Source
             * @default not_applicable
             * @enum {string}
             */
            cascade_split_source: "user_input" | "router_output" | "not_applicable";
            /**
             * Distillation Training Cost Method
             * @description Accounting method and parameters for one-time distillation training run, if applicable.
             */
            distillation_training_cost_method?: string | null;
            /** @description Modeled one-time distillation training carbon with uncertainty range [low, high]. */
            distillation_training_carbon?: components["schemas"]["Quantity"] | null;
        };
        /** RegionOption */
        RegionOption: {
            /** Code */
            code: string;
            /** Name */
            name: string;
            /** Intensity Gco2 Per Kwh */
            intensity_gco2_per_kwh: number;
            /** Year */
            year: number;
        };
        /**
         * SystemInventory
         * @description Structured description of an AI system to audit.
         *
         *     Fields not present in a parsed config file stay None and are shown
         *     to the user as 'please confirm' in the UI.
         */
        SystemInventory: {
            model?: components["schemas"]["ModelSpec"] | null;
            training?: components["schemas"]["TrainingConfig"] | null;
            inference?: components["schemas"]["InferenceConfig"] | null;
            /**
             * Region
             * @description Primary deployment region. Used for grid intensity lookup.
             * @default global
             */
            region: string;
            /**
             * Retraining Frequency Days
             * @description How often the model is retrained. None means no retraining.
             */
            retraining_frequency_days?: number | null;
            /**
             * Storage Tb
             * @description Storage footprint in TB (model weights, data, checkpoints).
             */
            storage_tb?: number | null;
            /**
             * Network Requests Per Day
             * @description Daily request count for network transfer estimation.
             */
            network_requests_per_day?: number | null;
            /**
             * Accuracy Floor
             * @description Minimum acceptable accuracy (0-1). Recommender excludes configs below this.
             */
            accuracy_floor?: number | null;
            /**
             * Distillation Training Hours
             * @description Customizable distillation training run hours (default 50.0h).
             */
            distillation_training_hours?: number | null;
            /**
             * Note
             * @description Free-text notes from config parser.
             * @default
             */
            note: string;
        };
        /**
         * Tier
         * @description Whether the number came from direct measurement or computation.
         * @enum {string}
         */
        Tier: "measured" | "modeled";
        /** TrainingConfig */
        TrainingConfig: {
            gpu: components["schemas"]["GPUSpec"];
            /** Duration Hours */
            duration_hours: number;
            /**
             * Pue
             * @description Override datacenter PUE for training.
             */
            pue?: number | null;
            /**
             * Region
             * @description Override region for training grid intensity.
             */
            region?: string | null;
            /**
             * N Epochs
             * @default 1
             */
            n_epochs: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** Verdict */
        Verdict: {
            label: components["schemas"]["VerdictLabel"];
            /**
             * Resolved By
             * @enum {string}
             */
            resolved_by: "rules" | "classifier" | "llm";
            /** Reason Chain */
            reason_chain: components["schemas"]["ReasonStep"][];
            /**
             * Confidence
             * @description Confidence [0,1]. None means the check is deterministic.
             */
            confidence?: number | null;
            /**
             * Schema Version
             * @default 1
             */
            schema_version: number;
        };
        /**
         * VerdictLabel
         * @enum {string}
         */
        VerdictLabel: "supported" | "contradicted" | "suspicious_boundary_shift" | "insufficient_evidence";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    get_regions_api_v1_regions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
        };
    };
    get_metadata_and_presets_api_v1_presets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetadataResponse"];
                };
            };
        };
    };
    get_metadata_and_presets_api_v1_meta_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetadataResponse"];
                };
            };
        };
    };
    calculate_ledger_api_v1_ledger_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LedgerRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LedgerResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    check_efficiency_claim_api_v1_claims_check_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClaimToLedgerMapping"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Verdict"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    extract_claim_api_v1_claims_extract_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExtractClaimRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Claim"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recommend_architectures_api_v1_recommend_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecommendRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParetoResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
